---
- name: "Flipping the screen"
  lineinfile:
    path: /boot/config.txt
    regex: '^display_rotate='
    line: "display_rotate=3"

- name: "Applying changes"
  reboot:
    reboot_timeout: 50

- include_tasks: chromium.yml
